### ISSUE TITLE
Feature Request: toggle option to remove brackets from track info

### ISSUE THREAD

**Issue by RadioWavetable** [e1miran/Now-Playing-Serato#9]
Hi,

You asked to open a new issue for feature requests, so here we go :-)

I was wondering if there's a possibility to add an option to toggle on/off to remove anything in between brackets in the track info. Let me explain.

Many of my tracks contain extra info in between brackets which is valuable for me, but not always for the listener/viewer. (e.g.: "TrackTitle-TrackArtist(mixinfo).mp3" results in "TrackTitle-TrackArtist(mixinfo)" in your app. It would be nice if we could filter out this info in between brackets. This then would result into "TrackTitle-TrackArtist" in the txt file, no matter what was in between brackets.

I understand not everybody might need or even want this feature. There for I was thinking to make this a toggle option so anyone can decide for themselves whether they want to use the feature or not.

Looking forward to your response.

Thanks in advance for looking into the possibilities!

Kind regards

**Comment by e1miran** [comment]
While I see the usefulness in this, everyone has different ways of tagging their song files, "( )" vs "[ ]", featured artists names, etc.  Implementing this may open up numerous requests for other customizations that are better handled by the users cleaning up their song tags.  

Plus this really is not within the scope of the tool since it can be achieved outside of it: i.e: re-tagging and using other tag fields such as "comments" for this extra song info.  Tools like mp3tag, just to name an example, exist that allow one to batch rename and tag files using custom filters and criteria.
